ch99/blog/urls.py
from django.urls import path, re_path
# from blog.views import PostLV, PostDV, PostAV, PostYAV, PostMAV, PostDAV, PostTAV
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name = 'index'),
    # /blog/
    path('post/', views.PostLV.as_view(), name = 'post_list'),
    # /blog/post/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name = 'post_detail'), #파이썬 정규 표현식
    # /blog/post/'뚫리지 않는 방패'…양자 시대 준비하는 이통3사(종합)/
    path('archive/', views.PostAV.as_view(), name = 'post_archive'),
    # /blog/archive/
    path('archive/<int:year>/', views.PostYAV.as_view(), name = 'post_year_archive'),
    # /blog/archive/2021/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name = 'post_month_archive'),
    # /blog/archive/2021/jul/
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name = 'post_day_archive'),
    # /blog/archive/2021/jul/05/
    path('archive/today/', views.PostTAV.as_view(), name = 'post_today_archive'),
    # /blog/archive/today/
]

ch99/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('bookmark/', include)'bookmark.urls')),
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from mysite.views import HomeView

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]
# 58페이지 교재

# path('bookmark/', BookmarkLV.as_view(), name='index'),
# path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),

ch99/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', max_length=50, unique=True, allow_unicode=True, help_text='one word for title alies.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    # 내부 클래스
    # 필드 속성 외 필요 데이터(파라미터) 사용 목적
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'       # 디폴트 값 : 앱명_모델클래스명
        ordering = ('-modify_dt',)    # 정렬 (날짜순)

    def __str__(self):
        return self.title

    # 메소드가 정의된 객체를 지칭하는 url 반환
    # 제목에서 중요 단어를 뽑아서 만든 슬러그를 주소창에서 사용할 url로 지정
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    # modify_dt를 기준으로 최신 포스트 반환
    def get_previous(self):
        return self.get_previous_by_modify_dt()

    # modify_dt를 기준으로 예전 포스트 반환
    def get_next(self):
        return self.get_next_by_modify_dt()

ch99/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    def __str__(self):
        return self.title

ch99/polls/models.py
from django.db import models

# Create your models here.

ch99/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# Create your views here.
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
# from models import Post
from blog.models import Post

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2    #한 페이지에 보이는 글 개수 설정

class PostDV(DetailView):
    model = Post
    #template_name = 'post_detail.html'

class PostAV(ArchiveIndexView):
    model = Post
    # template_name = 'post_archive.html'
    date_field = 'modify_dt' # 기준 날짜, 날짜별로 정리


class PostYAV(YearArchiveView):
    model = Post
    # template_name = 'post_archive_year.html'
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    # template_name = 'post_archive_month.html'
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    # template_name = 'post_archive_day.html'
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    # template_name = 'post_archive_day.html'
    date_field = 'modify_dt'

ch99/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark       #표
    #template name = 'bookmark[모델명] list.html'
    #context object name = 'object list'

class BookmarkDV(DetailView):
    model = Bookmark

ch99/mysite/views.py
from django.views.generic import TemplateView




class HomeView(TemplateView):
    template_name = 'home.html'

ch99/polls/views.py
from django.shortcuts import render

# Create your views here.

ch99/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">

<!-- home.html 파일 입니다.-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
<!--    사이트 제목 문구 수정-->
    <span class = "navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming
    </span>

<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarSupportedContent">-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
<!--        메뉴 제목 수정-->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
        </li>

        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="">Photo</a>
        </li>

<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Link</a>-->
<!--        </li>-->


        <li class="nav-item dropdown mx-1 btn btn-primary">
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">-->
<!--            Dropdown-->
<!--          </a>-->
          <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">Util</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                <li><a class="dropdown-item" href="">Search</a></li>
            </ul>
        </li>
        <li class="nav-item">
<!--          <a class="nav-link disabled" href="#" tabindex="-1">Disabled</a>-->
        </li>
      </ul>
      <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
<!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
      </form>
    </div>
    </nav>
    <div class = "container">
        {% block content %}
<!--        <h4>This is CONTENT area.</h4>-->
        {% endblock %}
    </div>
    {% block footer %}
    <footer class = "fix-bottom bg-info">

<!--        <h4>This is FOOTER area.</h4>-->
    {% endblock %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js">
    </script>
    {% block extra-script %}{% endblock %}
</body>
</html>

ch99/blog/templates/base_변경전.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Wen Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">

<!-- home.html 파일 입니다.-->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">

    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link active" href="#">Home <span class = "sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
            Dropdown
          </a>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    </nav>
    <div class = "container bg-warning">
        {% block content %}
<!--        <h4>This is CONTENT area.</h4>-->
        {% endblock %}
    </div>
    {% block footer %}
    <footer class = "fix-bottom bg-info">

<!--        <h4>This is FOOTER area.</h4>-->
    {% endblock %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js">
    </script>
    {% block extra-script %}{% endblock %}
</body>
</html>

ch99/blog/templates/blog/backup/post_all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Blog List</h1>
<br>

<!--{{ 변수 }} 템블릿 태그-->

<!--# Post 테이블의 내용(글)을 나열-->

<!--{% for 변수 in 리스트%}-->
<!--{% endfor %}-->

{% for post in posts %}
     <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
     {{ post.modify_dt }}
     <p>{{ post.description }}</p>
{% endfor %}

<!--# 페이지 이동 링크(다음페이지, 이전페이지)-->

<!--1페이지에서 본 화면 내용-->
<!--Page 1 of 3 NextPage-->

<!--2페이지에서 본 화면 내용-->
<!--PreviousPage Page 2 of 3 NextPage-->

<!--3페이지에서 본 화면 내용-->
<!--PreviousPage Page 3 of 3-->

<!--{% if 조건 %}-->
<!--{% endif %}-->

<!--page_obj 는 장고 Page 객체가 들어있는 컨택스트 변수-->
<!--현재 페이지 기준으로 이전페이지가 있는지 확인-->
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
{% endif %}

<!--현재 페이지 번호-->
<!--Page 현재페이지 of 전체페이지-->
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
<!--현재 페이지 기준으로 다음 페이지가 있늕 확인-->
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number}}">NextPage</a>
{% endif %}
</body>
</html>


<!--ListView에서 Pagination 사용 가능-->
<!--Pagination 사용하려면 Paginate_by 변수 추가-->
<!--** Page 클래스-->
<!--page_obj 이름으로 포함-->

<!-- -포함 메서드-->
<!--Page.has_next()              :다음페이지가 있으면 True 반환-->
<!--Page.has_previous()           :이전페이지가 있으면 True 반환-->
<!--Page.next_page_number()        :다음페이지가 있으면 페이지 번호 반환-->
<!--Page.previous_page_number()     :이전페이지가 있으면 페이지 번호 반환-->

<!-- -포함 맴버변수-->
<!--page_number-->
<!--page_paginate-->

ch99/blog/templates/blog/backup/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
            Year-{{ date|date:"Y" }}
        </a>
    </li>
    {% endfor %}
</ul>
<br>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

ch99/blog/templates/blog/backup/post_archive_day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<ul>
    {% for post in object_list %}
    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
    {% endfor %}
</ul>
</body>
</html>

ch99/blog/templates/blog/backup/post_archive_month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<ul>
    {% for post in object_list %}
    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
    {% endfor %}
</ul>
</body>
</html>

ch99/blog/templates/blog/backup/post_archive_year..html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Post Archives for {{ year|date:"Y" }}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">
    {{ date|date:"F" }} </a></li>
    {% endfor %}
</ul>
<br>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</body>
</html>

ch99/blog/templates/blog/backup/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            &laquo;-- {{ object.get_previous }}
        </a>
    {% endif %}

    {% if object.get_next %}
    |   <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{ object.get_next }} --&raquo;
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:"j F Y" }}</p>
<br>
<!--포스트 객체의 내용을 출력-->
<!--linebreaks 템플릿 필터는 \n(new line)을 인식-->
    {{ object.content|linebreaks }}

</body>
</html>

ch99/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}" class="btn btn-outline-primary btn-sm mx-1">
            Year-{{ date|date:"Y" }}
        </a>
    </li>
    {% endfor %}
</ul>
<br>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
    copyright &copy; 2022 DjangoBook by gydori
</footer>
{% endblock %}


<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Post Archives until {% now "N d, Y" %}</h1>-->
<!--<ul>-->
<!--    {% for date in date_list %}-->
<!--    <li style="display: inline;">-->
<!--        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">-->
<!--            Year-{{ date|date:"Y" }}-->
<!--        </a>-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--<br>-->
<!--    <ul>-->
<!--        {% for post in object_list %}-->
<!--        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;-->
<!--            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong>-->
<!--            </a>-->
<!--        </li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--</body>-->
<!--</html>-->

ch99/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<ul>
    {% for post in object_list %}
    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
    {% endfor %}
</ul>
{% endblock %}
{% block footer %}
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
    copyright &copy; 2022 DjangoBook by gydori
</footer>
{% endblock %}




<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>-->
<!--<ul>-->
<!--    {% for post in object_list %}-->
<!--    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;-->
<!--    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--</body>-->
<!--</html>-->

ch99/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<ul>
    {% for post in object_list %}
    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
    {% endfor %}
</ul>
{% endblock %}
{% block footer %}
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
    copyright &copy; 2022 DjangoBook by gydori
</footer>
{% endblock %}







<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->

<!--<body>-->
<!--<h1>Post Archives for {{ month|date:"N, Y" }}</h1>-->
<!--<ul>-->
<!--    {% for post in object_list %}-->
<!--    <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;-->
<!--    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--</body>-->
<!--</html>-->

ch99/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}" class="btn btn-outline-primary btn-sm mx-1">
    {{ date|date:"F" }} </a></li>
    {% endfor %}
</ul>
<br>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
    copyright &copy; 2022 DjangoBook by gydori
</footer>
{% endblock %}




<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Post Archives for {{ year|date:"Y" }}</h1>-->
<!--<ul>-->
<!--    {% for date in date_list %}-->
<!--    <li style="display: inline;">-->
<!--        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">-->
<!--    {{ date|date:"F" }} </a></li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--<br>-->
<!--    <ul>-->
<!--        {% for post in object_list %}-->
<!--        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;-->
<!--        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--</body>-->
<!--</html>-->

ch99/bookmark/templates/bookmark/backup/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark</title>
</head>
<body>
    <div>
        <h1>Bookmak List</h1>
        <ul>
            {% for bookmark in object_list %}
            <li>
                {# % url 'namespace:view-name arg1 arg2 % #}
                <a href="{% url 'bookmark:detail' bookmark.id %}">
                {{ bookmark.title }}
                {{ bookmark.id }}
                {{ bookmark.url }}
            </a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

ch99/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}
    <h1>Bookmark List</h1>
    <br>
    <ul>
            {% for bookmark in object_list %}
            <li>
                <a href="{% url 'bookmark:detail' bookmark.id %}">
                {{ bookmark.title }}

            </a></li>
            {% endfor %}
    </ul>
{% endblock %}
{% block footer %}
<footer class="fixed-bottom bg-info">
    <h4>This is FOOTER area.</h4>
    copyright &copy; 2022 DjangoBook by gydori
</footer>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Django Bookmark</title>-->
<!--</head>-->
<!--<body>-->
<!--    <div>-->
<!--        <h1>Bookmak List</h1>-->
<!--        <ul>-->
<!--            {% for bookmark in object_list %}-->
<!--            <li>-->
<!--                {# % url 'namespace:view-name arg1 arg2 % #}-->
<!--                <a href="{% url 'bookmark:detail' bookmark.id %}">-->
<!--                {{ bookmark.title }}-->
<!--                {{ bookmark.id }}-->
<!--                {{ bookmark.url }}-->
<!--            </a></li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--    </div>-->
<!--</body>-->
<!--</html>-->